[[streams]]
city   = "Varied"
label  = "Yoo"
link   = "https://twitch.tv/wuubi"
notes  = "Live code/etc streams from around the world."
source = "wuu.bi"

[[streams]]
kind  = "web"
label = "zombocom"
link  = "https://html5zombo.com"
